// Cantonal seats (cabeceras cantonales) of Ecuador, grouped by province.
// 221 cities across 24 provinces. Cities are sorted alphabetically within each province.

export type ProvinceCities = {
  province: string
  cities: readonly string[]
}

export const ECUADOR_CITIES_BY_PROVINCE: readonly ProvinceCities[] = [
  {
    province: 'Azuay',
    cities: [
      'Camilo Ponce Enríquez',
      'Chordeleg',
      'Cuenca',
      'El Pan',
      'Girón',
      'Guachapala',
      'Gualaceo',
      'Nabón',
      'Oña',
      'Paute',
      'Pucará',
      'San Fernando',
      'Santa Isabel',
      'Sevilla de Oro',
      'Sígsig',
    ],
  },
  {
    province: 'Bolívar',
    cities: ['Caluma', 'Chillanes', 'Echeandía', 'Guaranda', 'Las Naves', 'San José de Chimbo', 'San Miguel'],
  },
  {
    province: 'Cañar',
    cities: ['Azogues', 'Biblián', 'Cañar', 'Déleg', 'El Tambo', 'La Troncal', 'Suscal'],
  },
  {
    province: 'Carchi',
    cities: ['Bolívar', 'El Ángel', 'Mira', 'San Gabriel', 'San Pedro de Huaca', 'Tulcán'],
  },
  {
    province: 'Chimborazo',
    cities: [
      'Alausí',
      'Cajabamba',
      'Chambo',
      'Chunchi',
      'Cumandá',
      'Guamote',
      'Guano',
      'Pallatanga',
      'Penipe',
      'Riobamba',
    ],
  },
  {
    province: 'Cotopaxi',
    cities: ['La Maná', 'Latacunga', 'Pangua', 'Pujilí', 'Salcedo', 'Saquisilí', 'Sigchos'],
  },
  {
    province: 'El Oro',
    cities: [
      'Arenillas',
      'Atahualpa',
      'Balsas',
      'Chilla',
      'El Guabo',
      'Huaquillas',
      'La Victoria de Las Lajas',
      'Machala',
      'Marcabelí',
      'Pasaje',
      'Piñas',
      'Portovelo',
      'Santa Rosa',
      'Zaruma',
    ],
  },
  {
    province: 'Esmeraldas',
    cities: ['Atacames', 'Esmeraldas', 'Limones', 'Muisne', 'Quinindé', 'Río Verde', 'San Lorenzo'],
  },
  {
    province: 'Galápagos',
    cities: ['Puerto Ayora', 'Puerto Baquerizo Moreno', 'Puerto Villamil'],
  },
  {
    province: 'Guayas',
    cities: [
      'Balao',
      'Balzar',
      'Bucay',
      'Colimes',
      'Coronel Marcelino Maridueña',
      'Daule',
      'Durán',
      'El Empalme',
      'El Triunfo',
      'Guayaquil',
      'Isidro Ayora',
      'Jujan',
      'Lomas de Sargentillo',
      'Milagro',
      'Naranjal',
      'Naranjito',
      'Nobol',
      'Palestina',
      'Pedro Carbo',
      'Playas',
      'Salitre',
      'Samborondón',
      'Santa Lucía',
      'Simón Bolívar',
      'Yaguachi',
    ],
  },
  {
    province: 'Imbabura',
    cities: ['Atuntaqui', 'Cotacachi', 'Ibarra', 'Otavalo', 'Pimampiro', 'Urcuquí'],
  },
  {
    province: 'Loja',
    cities: [
      'Alamor',
      'Amaluza',
      'Cariamanga',
      'Catacocha',
      'Catamayo',
      'Celica',
      'Chaguarpamba',
      'Gonzanamá',
      'Loja',
      'Macará',
      'Olmedo',
      'Pindal',
      'Quilanga',
      'Saraguro',
      'Sozoranga',
      'Zapotillo',
    ],
  },
  {
    province: 'Los Ríos',
    cities: [
      'Babahoyo',
      'Baba',
      'Buena Fe',
      'Catarama',
      'Mocache',
      'Montalvo',
      'Palenque',
      'Puebloviejo',
      'Quevedo',
      'Quinsaloma',
      'Valencia',
      'Ventanas',
      'Vinces',
    ],
  },
  {
    province: 'Manabí',
    cities: [
      'Bahía de Caráquez',
      'Calceta',
      'Chone',
      'El Carmen',
      'Flavio Alfaro',
      'Jama',
      'Jaramijó',
      'Jipijapa',
      'Junín',
      'Manta',
      'Montecristi',
      'Olmedo',
      'Paján',
      'Pedernales',
      'Pichincha',
      'Portoviejo',
      'Puerto López',
      'Rocafuerte',
      'San Vicente',
      'Santa Ana',
      'Sucre',
      'Tosagua',
    ],
  },
  {
    province: 'Morona Santiago',
    cities: [
      'Gualaquiza',
      'Huamboya',
      'Logroño',
      'Macas',
      'Méndez',
      'Pablo Sexto',
      'Palora',
      'Plaza Gutiérrez',
      'San Juan Bosco',
      'Sucúa',
      'Taisha',
      'Tiwintza',
    ],
  },
  {
    province: 'Napo',
    cities: ['Archidona', 'Baeza', 'Carlos Julio Arosemena Tola', 'El Chaco', 'Tena'],
  },
  {
    province: 'Orellana',
    cities: ['La Joya de los Sachas', 'Loreto', 'Nuevo Rocafuerte', 'Puerto Francisco de Orellana'],
  },
  {
    province: 'Pastaza',
    cities: ['Arajuno', 'Mera', 'Puyo', 'Santa Clara'],
  },
  {
    province: 'Pichincha',
    cities: [
      'Cayambe',
      'Machachi',
      'Pedro Vicente Maldonado',
      'Puerto Quito',
      'Quito',
      'San Miguel de los Bancos',
      'Sangolquí',
      'Tabacundo',
    ],
  },
  {
    province: 'Santa Elena',
    cities: ['La Libertad', 'Salinas', 'Santa Elena'],
  },
  {
    province: 'Santo Domingo de los Tsáchilas',
    cities: ['La Concordia', 'Santo Domingo'],
  },
  {
    province: 'Sucumbíos',
    cities: ['El Dorado de Cascales', 'La Bonita', 'Lago Agrio', 'Lumbaquí', 'Puerto El Carmen del Putumayo', 'Shushufindi', 'Tarapoa'],
  },
  {
    province: 'Tungurahua',
    cities: [
      'Ambato',
      'Baños de Agua Santa',
      'Cevallos',
      'Mocha',
      'Patate',
      'Pelileo',
      'Píllaro',
      'Quero',
      'Tisaleo',
    ],
  },
  {
    province: 'Zamora Chinchipe',
    cities: [
      '28 de Mayo',
      'El Pangui',
      'Guayzimi',
      'Palanda',
      'Paquisha',
      'Yantzaza',
      'Zamora',
      'Zumba',
      'Zumbi',
    ],
  },
] as const

export const ECUADOR_CITIES: readonly string[] = ECUADOR_CITIES_BY_PROVINCE.flatMap(
  (p) => p.cities,
)

const CITY_SET = new Set<string>(ECUADOR_CITIES)

export function isEcuadorCity(value: string): boolean {
  return CITY_SET.has(value)
}
